# Generated by Django 5.1.1 on 2024-09-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=30)),
                ('request_num', models.IntegerField()),
                ('stock_num', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('distributed_num', models.IntegerField()),
            ],
        ),
    ]
