# Generated by Django 5.1.1 on 2024-09-11 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='避難所の住所')),
            ],
        ),
        migrations.CreateModel(
            name='StoreAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='倉庫住所')),
            ],
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='category',
            field=models.CharField(max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='distributed_num',
            field=models.IntegerField(verbose_name='配分決定済み個数'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='item_name',
            field=models.CharField(max_length=30, verbose_name='物資名'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='request_num',
            field=models.IntegerField(verbose_name='必要個数'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='stock_num',
            field=models.IntegerField(verbose_name='残存数'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.requestadress', verbose_name='避難所の住所'),
        ),
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='カテゴリ')),
                ('item_name', models.CharField(max_length=30, verbose_name='商品名')),
                ('stock_num', models.IntegerField(verbose_name='在庫数')),
                ('latitude', models.IntegerField(verbose_name='緯度')),
                ('longitude', models.IntegerField(verbose_name='経度')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.storeadress', verbose_name='倉庫住所')),
            ],
        ),
    ]
