# Generated by Django 5.1.1 on 2024-09-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_requestadress_storeadress_alter_requestdata_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='distributed_num',
            field=models.IntegerField(default=0, verbose_name='配分決定済み個数'),
        ),
    ]
